# 서버 포트 설정
server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/spring?user=postgres&password=1234
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  profiles:
    include: aws, swagger, auth
  sql:
    init:
      mode: always

  thymeleaf:
    cache: false

jwt:
  secret: b552278a2c6f3a748a31f41b34ec5348ed6fa1b62ab77c28e7e64d1ae6adfc73